#!/bin/sh

# Python/Django

# FL-09-Dec-2015 Created
# FL-09-Dec-2015 Changed

export PYTHON_LOCAL=/home/fons/opt/Python/python-3.5.1

# 2.7.5 is the system python
#alias python=/usr/bin/python
alias python=$PYTHON_LOCAL/bin/python3.5

export PYTHON_SITEPACKS=$PYTHON_LOCAL/lib/python3.5/site-packages

export PYTHONPATH=$PYTHON_SITEPACKS

# do not append ${PATH} to avoid mixing python versions
export PATH=$PYTHON_LOCAL/bin:${PATH_AT_LOGIN}

export LD_LIBRARY_PATH=$PYTHON_LOCAL/lib

# [eof]
